server:
  port: 8888


spring:
  application:
    name: config-service
  profiles:
    active: native #
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\MSA-TIL\native-file-repo

        git:
          uri: https://github.com/pliot123/spring-cloud-config.git
#          username: [your username]
#          password: [your password]//private repo 일때

